Boolean indrxing .

In [37]:
import numpy as np

In [38]:
arr = np.array([10,15,20,25,30])

In [39]:
arr[[True,False,False,True,False]]

array([10, 25])

In [40]:
l=[True,False,True,True,False]
l

[True, False, True, True, False]

In [41]:
arr[l]

array([10, 20, 25])

In [42]:
arr

array([10, 15, 20, 25, 30])

In [43]:
l2=(arr%2==0)
l2

array([ True, False,  True, False,  True])

In [44]:
arr[l2]

array([10, 20, 30])

In [45]:
arr[arr%2==0]

array([10, 20, 30])

In [46]:
age=np.array([42,18,22,16,13])
age

array([42, 18, 22, 16, 13])

In [47]:
age[age>18]

array([42, 22])

In [48]:
age[age==22]

array([22])

In [49]:
a2=np.array([[3,5,7],[1,2,9],[6,4,2]])
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [50]:
l1=[True,False,True]

In [51]:
a2[l1]

array([[3, 5, 7],
       [6, 4, 2]])

Boolean mask (masking arrary)

In [52]:
arr

array([10, 15, 20, 25, 30])

In [53]:
l

[True, False, True, True, False]

In [54]:
print(np.ma.array(arr,mask=1))

[-- -- -- -- --]


In [55]:
add_numbers=np.ma.array(arr,mask=arr%2==0)

In [56]:
print(add_numbers)

[-- 15 -- 25 --]


Resgiping array

In [57]:
a2

array([[3, 5, 7],
       [1, 2, 9],
       [6, 4, 2]])

In [58]:
a2.flatten()

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [59]:
a2.reshape(-1)

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [60]:
a2.ravel()

array([3, 5, 7, 1, 2, 9, 6, 4, 2])

In [61]:
a1d=np.arange(12)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
a1d.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
a1d.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [64]:
a1d.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [65]:
a1d.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
a1d.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

BRODCASTING OF ARRAY .

Brodcasting is a powarfull meacanisiam in numpy that allows array opration between arrays of diffent shape without copying a data .

In simpal terms brodcasting allows you to automatically expend smaller arrays to match the shape of large array durring operations like addition ___ .

In [67]:
s1 = np.array ([[3,5,7],[1,2,3],[6,4,2]])
s1
l1=[True,False,True]
s1[l1]

array([[3, 5, 7],
       [6, 4, 2]])

In [70]:
s1 = [3]
s2=5
s3=np.array([6])

In [71]:
arr+s2

array([15, 20, 25, 30, 35])

In [72]:
arr+s1

array([13, 18, 23, 28, 33])

In [73]:
arr+8

array([18, 23, 28, 33, 38])

In [74]:
arr+s2

array([15, 20, 25, 30, 35])

Vactor brodcasting 

In [76]:
a1=np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
a2=np.array([10,20,30])
a2

array([10, 20, 30])

In [79]:
print(a1+a2)

[[11 22 33]
 [14 25 36]]


In [81]:
a1=np.array([[1,2,3],
            [4,5,6]
])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a2=np.array([10,20]).reshape(-1,1)
a2

array([[10],
       [20]])

In [84]:
print(a1+a2)

[[11 12 13]
 [24 25 26]]


In [86]:
a2.shape=(2,1)
a2

array([[10],
       [20]])

Matrix brodcasting .

In [ ]:
a1=np.array([[1],[2]])
a2=np.array([[10],[20,30]])

In [87]:
print(a1)

[[1 2 3]
 [4 5 6]]


In [88]:
print()

In [89]:
print(a2)

[[10]
 [20]]


In [ ]:
print()

In [90]:
a3 =a1+a2

In [91]:
print(a3)

[[11 12 13]
 [24 25 26]]
